# This is a basic workflow to help you get started with Actions

name: Build Frontend

on: 
  push:
    tags:
    - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Install Zip
      - name: action-zip
        uses: montudor/action-zip@v1.0.0
        
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.8.0'
          
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      # Installs Depot Tools
      # echo "${pwd}/depot_tools" >> $GITHUB_PATH
      - name: Install Depot Tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "$(pwd)/depot_tools" >> $GITHUB_PATH
      # Build Devtools
      - name: Download Devtools
        run: |
          fetch devtools-frontend
          cd devtools-frontend
          git remote remove origin
          git remote add origin https://github.com/Liquid-Propulsion/devtools-frontend.git
          git fetch
          git checkout master
          git pull
          
      - name: Build Devtools
        run: |
          cd devtools-frontend
          npm run install-deps
          gn gen out/Default
          echo "is_debug=false" >> out/Default/args.gn
          autoninja -C out/Default
          
      - name: Zip Output
        run: |
          cd devtools-frontend/out/Default/gen
          mv front_end/nevermore_app.html front_end/index.html
          zip -qq -r release.zip front_end/*
        
      - name: Upload bundles to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: devtools-frontend/out/Default/gen/release.zip
          asset_name: release-bundle.zip
          tag: ${{ github.ref }}
